### ISSUE TITLE
I want to update mruby/c version to release2.1

### ISSUE THREAD

**Issue by 0cha** [gfd-dennou-club/iotex-esp32-mrubyc#1]
Can I upgrade to release 2.1 since the included mruby/c release 1.2 is a bit old?

**Comment by sugiymki** [comment]
Yes. Please upgrade to release 2.1.

**Comment by 0cha** [comment]
THX

- Update mruby/c to version 2.1.
- Fixed a couple of mrblib/models that didn't work.
- You can select to load models by #define and #ifdef in main.c
- Added an option to switch loops in Makefile
  - Execute it like "make adc flash -j9".
- Set the Flash memory usage area of ESP-WROOM-32 to 2MB so that all models can be read.
- Operation check with ESP-IDF v4.2

How about this?

https://github.com/0cha/iotex-esp32-mrubyc/commit/75fa05c355d86ed985f61a0189ce522273328a30

**Comment by sugiymki** [comment]
Thanks!  It's seems good!

**Comment by 0cha** [comment]
Ok. Then I'll send  a pull request.

https://github.com/gfd-dennou-club/iotex-esp32-mrubyc/pull/3

**Comment by sugiymki** [comment]
finished!
